namespaces:
  production:

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"

context: logging

apps:
  fluentd:
    enabled: true
    namespace: production
    chart: stable/fluentd
    version: "1.1.0"
    valuesFile: "values.yaml"
