namespaces:
  production:

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"

context: monitoring

apps:
  datadog:
    enabled: true
    namespace: production
    chart: stable/datadog
    version: "1.38.7"
    valuesFile: "values.yaml"
