namespaces:
  production:
  argocd:

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  jetstack: "https://charts.jetstack.io"
  jaegertracing: "https://jaegertracing.github.io/helm-charts"
  argo: "https://argoproj.github.io/argo-helm"

context: infra

apps:
  fluentd:
    enabled: true
    namespace: production
    chart: stable/fluentd
    version: "1.1.0"
    valuesFiles: ["fluentd.values.yaml", "fluentd.values.TEST.yaml"]
  cert-manager:
    enabled: true
    namespace: production
    chart: jetstack/cert-manager
    version: "v0.12.0"
  jaeger:
    enabled: true
    namespace: production
    chart: jaegertracing/jaeger-operator
    version: "2.12.4"
  local-service:
    enabled: true
    namespace: production
    chart: ./local-service
    version: "1.0.1"
  argocd:
    enabled: true
    namespace: argocd
    chart: argo/argo-cd
    version: "2.0.0"
    valuesFile: "argocd-values.yaml"