namespaces:
  production:

helmRepos:
  stable: "https://charts.helm.sh/stable"

context: monitoring

apps:
  datadog:
    enabled: true
    namespace: production
    chart: stable/datadog
    version: "1.38.7"
    valuesFile: "datadog.values.yaml"
